#!/bin/bash
###############################################################################################################
# author: milesgratz
# website: serveradventures.com
# purpose: script to automate building SimpleInvoices web server on DigitalOcean droplet 
# links: https://github.com/simpleinvoices/simpleinvoices
# links: http://simpleinvoices.org/install
################################################################################################################

# determine OS 
dist=$(lsb_release -si)
ver=$(lsb_release -sr | cut -d. -f1)  

# check if Ubuntu 14+ or Debian 8+
if ([ $dist == 'Ubuntu' ] && ( [ $ver == '14' ] || [ $ver == '15' ] )) || ( [ $dist == 'Debian' ] && [ $ver == '8' ] )
then
  # detected compatible operating system
  echo '===================================================='
  echo 'Operating System: Ubuntu 14+ or Debian 8+'
  echo 
  echo   'Starting installation...'
  echo '===================================================='
  echo 

  # define mysql root password
  read -p "Please specify MySQL root password: " mysqlpwd

  # echo mysql root password to /var/cache/debconf/passwords.dat to prevent 'apt-get install mysql-server' prompting for root password
  echo mysql-server mysql-server/root_password password $mysqlpwd | debconf-set-selections
  echo mysql-server mysql-server/root_password_again password $mysqlpwd | debconf-set-selections

  # download simpleinvoices2011.1 (stable release) zip
  wget https://bitbucket.org/simpleinvoices/simpleinvoices/downloads/simpleinvoices.2011.1.zip

  # update and install lamp-server unzip
  apt-get upgrade && apt-get -y install unzip apache2 mysql-server php5 php-pear php5-mysql

  # unzip simpleinvoices2011.1 to /var/www/html
  unzip simpleinvoices.2011.1.zip -d /var/www/

  # grant privileges to apache2 user (www-data) to /var/www/simpleinvoices
  chown www-data:www-data /var/www/simpleinvoices

  # run "mysql_secure_installation"
  mysql --user="root" --password="$mysqlpwd" -e "UPDATE mysql.user SET Password=PASSWORD('"$mysqlpwd"') WHERE User='root'"
  mysql --user="root" --password="$mysqlpwd" -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
  mysql --user="root" --password="$mysqlpwd" -e "DELETE FROM mysql.user WHERE User=''"
  mysql --user="root" --password="$mysqlpwd" -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
  mysql --user="root" --password="$mysqlpwd" --execute="FLUSH PRIVILEGES;"

  # create simpleinvoices database, grant privileges, etc
  mysql --user="root" --password="$mysqlpwd" --execute="CREATE DATABASE simple_invoices;"
  mysql --user="root" --password="$mysqlpwd" --execute="GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP ON simple_invoices.* TO 'simple_invoices'@'localhost' IDENTIFIED BY   '"$mysqlpwd"';"
  mysql --user="root" --password="$mysqlpwd" --execute="FLUSH PRIVILEGES;"

  # create required database tables from simpleinvoices.2011.1.zip extract
  mysql --user="simple_invoices" --password="$mysqlpwd" simple_invoices < /var/www/simpleinvoices/databases/mysql/Full_Simple_Invoices.sql

  # create simpleinvoices.conf in /etc/apache2/sites-available
  echo '<VirtualHost *:80>' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # The ServerName directive sets the request scheme, hostname and port that' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # the server uses to identify itself. This is used when creating' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # redirection URLs. In the context of virtual hosts, the ServerName' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # specifies what hostname must appear in the request'\''s Host: header to' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # match this virtual host. For the default virtual host (this file) this' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # value is not decisive as it is used as a last resort host regardless.' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # However, you must set it for any further virtual host explicitly.' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      #ServerName www.example.com' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      ServerAdmin webmaster@localhost' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      DocumentRoot /var/www/simpleinvoices' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      <Directory />' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '            Options FollowSymLinks' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '            AllowOverride None' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      </Directory>' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      <Directory /var/www/>' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '             Options Indexes FollowSymLinks MultiViews' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '             AllowOverride None' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '             Order allow,deny' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '             allow from all' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      </Directory>' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      <Files config.ini>' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '             order allow,deny' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '             deny from all' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      </Files>' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # error, crit, alert, emerg.' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # It is also possible to configure the loglevel for particular' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # modules, e.g.' >> /etc/apache2/sites-available/simpleinvoices.conf >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      #LogLevel info ssl:warn' >> /etc/apache2/sites-available/simpleinvoices.conf >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      ErrorLog ${APACHE_LOG_DIR}/error.log' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      CustomLog ${APACHE_LOG_DIR}/access.log combined' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # For most configuration files from conf-available/, which are' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # enabled or disabled at a global level, it is possible to' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # include a line for only one particular virtual host. For example the' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # following line enables the CGI configuration for this host only' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      # after it has been globally disabled with "a2disconf".' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '      #Include conf-available/serve-cgi-bin.conf' >> /etc/apache2/sites-available/simpleinvoices.conf
  echo '</VirtualHost>' >> /etc/apache2/sites-available/simpleinvoices.conf

  # disable default site (000-default.conf) and enable simpleinvoices.conf
  a2dissite 000-default
  a2ensite simpleinvoices

  # fix mysql password for simpleinvoices config.ini
  sed -i -e "10s/$/\"$mysqlpwd\"/" /var/www/simpleinvoices/config/config.ini

  # fix mysql username to be 'simple_invoices' for simpleinvoices config.ini
  sed -i -e 's/root/simple_invoices/g' /var/www/simpleinvoices/config/config.ini

  # enable authentication for simpleinvoices config.ini
  sed -i -e '0,/false/s/false/true/' /var/www/simpleinvoices/config/config.ini

  # grant privileges to cache folder (/var/www/simpleinvoices/tmp/cache)
  chown -R www-data:www-data /var/www/simpleinvoices/tmp

  # restart apache2
  service apache2 restart
   
  # define IP address of server
  ip=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/')

  # script is finished
  echo '========================================================================'
  echo 'Completed.' 		
  echo   
  echo 'SimpleInvoices has been installed on this Droplet.' 
  echo "   Please visit http://$ip"
  echo
  echo 'Default login information:'
  echo '   Email address:   	demo@simpleinvoices.org'
  echo '   Password:		demo'
  echo 
  echo '========================================================================'

else
  # could not find compatible operating system
  echo '========================================================================'
  echo 'ERROR. Could not detect compatible operating system...' 		
  echo '========================================================================'

fi
