#!/bin/bash
###############################################################################################################
# author: milesgratz
# website: serveradventures.com
# purpose: script to automate building SimpleInvoices web server on DigitalOcean droplet (+ LetsEncrypt HTTPS)
# links: https://github.com/milesgratz/simpleinvoices-droplet
# links: https://github.com/simpleinvoices/simpleinvoices
# links: http://simpleinvoices.org/install
################################################################################################################

# set variables for totally automated script
mysqlpwd=''
domain=''
email=''

# determine OS 
dist=$(lsb_release -si)
ver=$(lsb_release -sr | cut -d. -f1)  

# check if Ubuntu 14+ or Debian 8+
if ([ $dist == 'Ubuntu' ] && ( [ $ver == '14' ] || [ $ver == '15' ] )) || ( [ $dist == 'Debian' ] && [ $ver == '8' ] )
then
  # detected compatible operating system
  echo '===================================================='
  echo 'Operating System: Ubuntu 14+ or Debian 8+'
  echo 
  echo   'Starting installation...'
  echo '===================================================='
  echo 

  # check if mysqlpwd was already defined, otherwise define it
  if [ -z "$mysqlpwd" ]; 
  then 
    read -p "Please specify a MySQL database password: " mysqlpwd
    if [ -z "$mysqlpwd" ];
      then
        echo '===================================================='
        echo 'Database password cannot be null. Exiting...'
        echo '===================================================='
      exit
    fi
  fi

  # check if domain name was already defined, otherwise define it
  if [ -z "$domain" ];
  then 
    read -p "Please server domain name: " domain
    if [ -z "$domain" ];
      then
        echo '===================================================='
        echo 'Domain name cannot be null. Exiting...'
        echo '===================================================='
      exit
    fi
  fi 

  # check if email was already defined, otherwise define it
  if [ -z "$email" ];
  then 
    read -p "Please enter email address for authorizing LetsEncrypt: " email
    if [ -z "$email" ];
      then
        echo '===================================================='
        echo 'Email address cannot be null. Exiting...'
        echo '===================================================='
      exit
    fi
  fi 

  # echo mysql root password to /var/cache/debconf/passwords.dat to prevent 'mysql-server' and 'phpmyadmin' prompting for root password
  echo "mysql-server mysql-server/root_password password $mysqlpwd" | debconf-set-selections
  echo "mysql-server mysql-server/root_password_again password $mysqlpwd" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/app-password-confirm password $mysqlpwd" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/mysql/admin-pass password $mysqlpwd" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/mysql/app-pass password $mysqlpwd" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections

  # update and install required packages
  apt-get update && apt-get -y install unzip apache2 mysql-server php5 php-pear php5-mysql phpmyadmin php5-xsl git

  # download simpleinvoices from github to /var/www/simpleinvoices
  git clone --recursive https://github.com/simpleinvoices/simpleinvoices /var/www/simpleinvoices

  # download LetsEncrypt from git
  git clone https://github.com/letsencrypt/letsencrypt /opt/letsencrypt

  # grant privileges to apache2 user (www-data) to /var/www/simpleinvoices
  chown -R www-data:www-data /var/www/simpleinvoices

  # run "mysql_secure_installation"
  mysql --user="root" --password="$mysqlpwd" --execute="UPDATE mysql.user SET Password=PASSWORD('$mysqlpwd') WHERE User='root'"
  mysql --user="root" --password="$mysqlpwd" --execute="DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
  mysql --user="root" --password="$mysqlpwd" --execute="DELETE FROM mysql.user WHERE User=''"
  mysql --user="root" --password="$mysqlpwd" --execute="DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
  mysql --user="root" --password="$mysqlpwd" --execute="FLUSH PRIVILEGES;"

  # create simpleinvoices database, grant privileges, etc
  mysql --user="root" --password="$mysqlpwd" --execute="CREATE DATABASE simple_invoices;"
  mysql --user="root" --password="$mysqlpwd" --execute="GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP ON simple_invoices.* TO 'simple_invoices'@'localhost' IDENTIFIED BY '$mysqlpwd';"
  mysql --user="root" --password="$mysqlpwd" --execute="FLUSH PRIVILEGES;"

  # create LetsEncrypt config file
  echo 'authenticator = standalone' >> /opt/letsencrypt/$(hostname).ini 
  echo 'webroot-path = /var/www/simpleinvoices' >> /opt/letsencrypt/$(hostname).ini
  echo 'renew-by-default' >> /opt/letsencrypt/$(hostname).ini
  echo 'agree-tos' >> /opt/letsencrypt/$(hostname).ini
  echo "email = $email" >> /opt/letsencrypt/$(hostname).ini
  echo "domain = $domain" >> /opt/letsencrypt/$(hostname).ini

  # create LetsEncrypt certificate
  service apache2 stop 
  /opt/letsencrypt/letsencrypt-auto certonly --config /opt/letsencrypt/$(hostname).ini

  # create simpleinvoices.conf in /etc/apache2/sites-available
  cd /etc/apache2/sites-available
  echo '<VirtualHost *:80>' >> simpleinvoices.conf
  echo "      ServerName $domain" >> simpleinvoices.conf
  echo '      DocumentRoot /var/www/simpleinvoices' >> simpleinvoices.conf
  echo '      # disable .htaccess override' >> simpleinvoices.conf      
  echo '      <Directory /var/www/simpleinvoices>' >> simpleinvoices.conf
  echo '            AllowOverride None' >> simpleinvoices.conf
  echo '      </Directory>' >> simpleinvoices.conf
  echo '' >> simpleinvoices.conf
  echo '      # redirect to https' >> simpleinvoices.conf
  echo "      Redirect / https://$domain" >> simpleinvoices.conf
  echo '</VirtualHost>' >> simpleinvoices.conf
  echo '' >> simpleinvoices.conf
  echo '<VirtualHost *:443>' >> simpleinvoices.conf
  echo '      # The ServerName directive sets the request scheme, hostname and port that' >> simpleinvoices.conf
  echo '      # the server uses to identify itself. This is used when creating' >> simpleinvoices.conf
  echo '      # redirection URLs. In the context of virtual hosts, the ServerName' >> simpleinvoices.conf
  echo '      # specifies what hostname must appear in the request'\''s Host: header to' >> simpleinvoices.conf
  echo '      # match this virtual host. For the default virtual host (this file) this' >> simpleinvoices.conf
  echo '      # value is not decisive as it is used as a last resort host regardless.' >> simpleinvoices.conf
  echo '      # However, you must set it for any further virtual host explicitly.' >> simpleinvoices.conf
  echo '      #ServerName www.example.com' >> simpleinvoices.conf
  echo '' >> simpleinvoices.conf
  echo "      ServerName $domain" >> simpleinvoices.conf
  echo '      ServerAdmin webmaster@localhost' >> simpleinvoices.conf
  echo '      DocumentRoot /var/www/simpleinvoices' >> simpleinvoices.conf
  echo '' >> simpleinvoices.conf
  echo '      # define LetsEncrypt SSL certificates' >> simpleinvoices.conf
  echo '      SSLEngine On' >> simpleinvoices.conf
  echo "      SSLCertificateKeyFile /etc/letsencrypt/live/$domain/privkey.pem" >> simpleinvoices.conf
  echo "      SSLCertificateFile /etc/letsencrypt/live/$domain/cert.pem" >> simpleinvoices.conf
  echo "      SSLCertificateChainFile /etc/letsencrypt/live/$domain/chain.pem" >> simpleinvoices.conf
  echo '' >> simpleinvoices.conf
  echo '      #Allow .htaccess files to override' >> simpleinvoices.conf
  echo '      <Directory /var/www/simpleinvoices>' >> simpleinvoices.conf
  echo '            Options FollowSymLinks' >> simpleinvoices.conf
  echo '            AllowOverride All' >> simpleinvoices.conf
  echo '        #Block access to reading .htaccess files' >> simpleinvoices.conf
  echo '        <Files ~ "^\.ht">' >> simpleinvoices.conf
  echo '             Order allow,deny' >> simpleinvoices.conf
  echo '             Deny from all' >> simpleinvoices.conf
  echo '             Satisfy all' >> simpleinvoices.conf
  echo '        </Files>' >> simpleinvoices.conf
  echo '      </Directory>' >> simpleinvoices.conf
  echo '' >> simpleinvoices.conf
  echo '      # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,' >> simpleinvoices.conf
  echo '      # error, crit, alert, emerg.' >> simpleinvoices.conf
  echo '      # It is also possible to configure the loglevel for particular' >> simpleinvoices.conf
  echo '      # modules, e.g.' >> simpleinvoices.conf >> simpleinvoices.conf
  echo '      #LogLevel info ssl:warn' >> simpleinvoices.conf >> simpleinvoices.conf
  echo '' >> simpleinvoices.conf
  echo '      ErrorLog ${APACHE_LOG_DIR}/error.log' >> simpleinvoices.conf
  echo '      CustomLog ${APACHE_LOG_DIR}/access.log combined' >> simpleinvoices.conf
  echo '' >> simpleinvoices.conf
  echo '      # For most configuration files from conf-available/, which are' >> simpleinvoices.conf
  echo '      # enabled or disabled at a global level, it is possible to' >> simpleinvoices.conf
  echo '      # include a line for only one particular virtual host. For example the' >> simpleinvoices.conf
  echo '      # following line enables the CGI configuration for this host only' >> simpleinvoices.conf
  echo '      # after it has been globally disabled with "a2disconf".' >> simpleinvoices.conf
  echo '      #Include conf-available/serve-cgi-bin.conf' >> simpleinvoices.conf
  echo '</VirtualHost>' >> simpleinvoices.conf

  # enable SSL mod (HTTPS)
  a2enmod ssl

  # enable rewrite (.htaccess)
  a2enmod rewrite
 
  # create .htaccess files to prevent viewing simpleinvoices directories
  echo "Options -Indexes" > /var/www/simpleinvoices/.htaccess

  # disable default site (000-default.conf) and enable simpleinvoices.conf
  a2dissite 000-default
  a2ensite simpleinvoices
 
  # enable php5-mcrypt extension
  php5enmod mcrypt

  # fix mysql password for simpleinvoices config.php
  sed -i -e "s|''|'$mysqlpwd'|g" /var/www/simpleinvoices/config/config.php

  # fix mysql username to be 'simple_invoices' for simpleinvoices config.php
  sed -i -e 's/root/simple_invoices/g' /var/www/simpleinvoices/config/config.php

  # enable authentication for simpleinvoices config.php
  sed -i -e '0,/false/s/false/true/' /var/www/simpleinvoices/config/config.php

  # update username/password for phpmyadmin config.inc.php
  sed -i -e 's|$dbuser|root|g' /etc/phpmyadmin/config.inc.php
  sed -i -e "s|\$dbpwd|$mysqlpwd|g" /etc/phpmyadmin/config.inc.php

  # change default username from demo@simpleinvoices.org to $(hostname)@digitalocean.com
  cd /var/www/simpleinvoices/databases/mysql
  sed -i -e "s|demo\@simpleinvoices\.org|$(hostname)\@digitalocean.com|g" Full_Simple_Invoices.sql

  # create required database tables from source
  cd /var/www/simpleinvoices/databases/mysql
  mysql --user="simple_invoices" --password="$mysqlpwd" simple_invoices < Full_Simple_Invoices.sql

  # drop unwanted "demo" tables 
  mysql --user="root" --password="$mysqlpwd" --execute "TRUNCATE TABLE simple_invoices.si_biller;"
  mysql --user="root" --password="$mysqlpwd" --execute "TRUNCATE TABLE simple_invoices.si_customers;"
  mysql --user="root" --password="$mysqlpwd" --execute "TRUNCATE TABLE simple_invoices.si_inventory;"
  mysql --user="root" --password="$mysqlpwd" --execute "TRUNCATE TABLE simple_invoices.si_invoices;"
  mysql --user="root" --password="$mysqlpwd" --execute "TRUNCATE TABLE simple_invoices.si_invoice_items;"
  mysql --user="root" --password="$mysqlpwd" --execute "TRUNCATE TABLE simple_invoices.si_payment;"
  mysql --user="root" --password="$mysqlpwd" --execute "TRUNCATE TABLE simple_invoices.si_products;"
  mysql --user="root" --password="$mysqlpwd" --execute "TRUNCATE TABLE simple_invoices.si_products_attributes;"
  mysql --user="root" --password="$mysqlpwd" --execute "TRUNCATE TABLE simple_invoices.si_products_values;"

  # restart apache2
  service apache2 restart
  
  # define IP address of server
  ip=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/')

  # script is finished
  echo '========================================================================'
  echo 'SimpleInvoices has been installed. Default login below:' 
  echo
  echo "  Website URL:     https://$domain"
  echo "  Website IP:      http://$ip"
  echo "  Email address:   $(hostname)@digitalocean.com"
  echo '  Password:        demo'
  echo
  echo "  Database URL:    https://$domain/phpmyadmin"
  echo '  Username:        root'
  echo "  Password:        $mysqlpwd"  
  echo '========================================================================'

else
  # could not find compatible operating system
  echo '========================================================================'
  echo 'ERROR. Could not detect compatible operating system...' 		
  echo '========================================================================'

fi
